// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermanent = "permanent"

// Permanent mapped from table <permanent>
type Permanent struct {
	Key       string         `gorm:"column:key;type:varchar(16);primaryKey" json:"key"`
	Lang      string         `gorm:"column:lang;type:varchar(16);not null" json:"lang"`
	Content   string         `gorm:"column:content;type:mediumtext;not null" json:"content"`
	Password  *string        `gorm:"column:password;type:varchar(32)" json:"password"`
	ClientIP  string         `gorm:"column:client_ip;type:varchar(64);not null" json:"client_ip"`
	Username  *string        `gorm:"column:username;type:varchar(16)" json:"username"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
}

// TableName Permanent's table name
func (*Permanent) TableName() string {
	return TableNamePermanent
}
