// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTemporary = "temporary"

// Temporary mapped from table <temporary>
type Temporary struct {
	Key          string     `gorm:"column:key;type:varchar(16);primaryKey" json:"key"`
	Lang         *string    `gorm:"column:lang;type:varchar(16)" json:"lang"`
	Content      *string    `gorm:"column:content;type:mediumtext" json:"content"`
	Password     *string    `gorm:"column:password;type:varchar(32)" json:"password"`
	ClientIP     *string    `gorm:"column:client_ip;type:varchar(64)" json:"client_ip"`
	Username     *string    `gorm:"column:username;type:varchar(16)" json:"username"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	ExpireSecond *int64     `gorm:"column:expire_second;type:bigint unsigned" json:"expire_second"`
	ExpireCount  *int64     `gorm:"column:expire_count;type:bigint unsigned" json:"expire_count"`
}

// TableName Temporary's table name
func (*Temporary) TableName() string {
	return TableNameTemporary
}
